export const MENU = [
  { id: 'esp', name: 'Espresso', price: 4000, station: 'barra', cat: 'Café' },
  { id: 'ame', name: 'Americano', price: 4500, station: 'barra', cat: 'Café' },
  { id: 'cap', name: 'Capuchino', price: 6000, station: 'barra', cat: 'Café' },
  { id: 'lat', name: 'Latte', price: 6500, station: 'barra', cat: 'Café' },
  { id: 'moc', name: 'Mocha', price: 7000, station: 'barra', cat: 'Café' },
  { id: 'cho', name: 'Chocolate caliente', price: 5500, station: 'barra', cat: 'Bebidas calientes' },
  { id: 'te', name: 'Té', price: 3500, station: 'barra', cat: 'Bebidas calientes' },
  { id: 'jug', name: 'Jugo natural', price: 5000, station: 'barra', cat: 'Bebidas frías' },
  { id: 'lim', name: 'Limonada', price: 4500, station: 'barra', cat: 'Bebidas frías' },
  { id: 'gas', name: 'Gaseosa', price: 3500, station: 'barra', cat: 'Bebidas frías' },
  { id: 'frc', name: 'Frappé de café', price: 8500, station: 'cocina', cat: 'Frappés' },
  { id: 'frch', name: 'Frappé de chocolate', price: 8500, station: 'cocina', cat: 'Frappés' },
  { id: 'frf', name: 'Frappé de fresa', price: 8500, station: 'cocina', cat: 'Frappés' },
  { id: 'hcl', name: 'Hamburguesa clásica', price: 14000, station: 'cocina', cat: 'Comida rápida' },
  { id: 'hdb', name: 'Hamburguesa doble', price: 18000, station: 'cocina', cat: 'Comida rápida' },
  { id: 'spo', name: 'Sandwich de pollo', price: 12000, station: 'cocina', cat: 'Comida rápida' },
  { id: 'smx', name: 'Sandwich mixto', price: 10000, station: 'cocina', cat: 'Comida rápida' },
  { id: 'pap', name: 'Papas fritas', price: 6000, station: 'cocina', cat: 'Comida rápida' },
  { id: 'per', name: 'Perro caliente', price: 9000, station: 'cocina', cat: 'Comida rápida' },
  { id: 'wra', name: 'Wrap de pollo', price: 11000, station: 'cocina', cat: 'Comida rápida' },
  { id: 'pos1', name: 'Torta de chocolate', price: 7000, station: 'cocina', cat: 'Postres' },
  { id: 'pos2', name: 'Cheesecake', price: 8000, station: 'cocina', cat: 'Postres' },
];
